# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  NetCodeServer_config = debug
endif
ifeq ($(config),release)
  NetCodeServer_config = release
endif

PROJECTS := NetCodeServer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

NetCodeServer:
ifneq (,$(NetCodeServer_config))
	@echo "==== Building NetCodeServer ($(NetCodeServer_config)) ===="
	@${MAKE} --no-print-directory -C . -f NetCodeServer.make config=$(NetCodeServer_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f NetCodeServer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   NetCodeServer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"